# Generated by Django 4.2 on 2026-03-03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mitglieder", "0008_remove_mitglied_jugend_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="JugendEvent",
            fields=[
                ("pkid", models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titel", models.CharField(max_length=255, verbose_name="Titel")),
                ("datum", models.DateField(verbose_name="Datum")),
                ("ort", models.CharField(blank=True, max_length=255, verbose_name="Ort")),
                (
                    "mitglieder_teilgenommen",
                    models.ManyToManyField(blank=True, related_name="jugend_events_neu", to="mitglieder.mitglied"),
                ),
            ],
            options={
                "ordering": ["-datum", "titel"],
            },
        ),
        migrations.CreateModel(
            name="JugendAusbildung",
            fields=[
                ("pkid", models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("erprobung_lv1", models.BooleanField(default=False)),
                ("erprobung_lv1_datum", models.DateField(blank=True, null=True)),
                ("erprobung_lv2", models.BooleanField(default=False)),
                ("erprobung_lv2_datum", models.DateField(blank=True, null=True)),
                ("erprobung_lv3", models.BooleanField(default=False)),
                ("erprobung_lv3_datum", models.DateField(blank=True, null=True)),
                ("erprobung_lv4", models.BooleanField(default=False)),
                ("erprobung_lv4_datum", models.DateField(blank=True, null=True)),
                ("erprobung_lv5", models.BooleanField(default=False)),
                ("erprobung_lv5_datum", models.DateField(blank=True, null=True)),
                ("wissentest_lv1", models.BooleanField(default=False)),
                ("wissentest_lv1_datum", models.DateField(blank=True, null=True)),
                ("wissentest_lv2", models.BooleanField(default=False)),
                ("wissentest_lv2_datum", models.DateField(blank=True, null=True)),
                ("wissentest_lv3", models.BooleanField(default=False)),
                ("wissentest_lv3_datum", models.DateField(blank=True, null=True)),
                ("wissentest_lv4", models.BooleanField(default=False)),
                ("wissentest_lv4_datum", models.DateField(blank=True, null=True)),
                ("wissentest_lv5", models.BooleanField(default=False)),
                ("wissentest_lv5_datum", models.DateField(blank=True, null=True)),
                ("fwtechnik_spiel_datum", models.DateField(blank=True, null=True)),
                ("fwtechnik_datum", models.DateField(blank=True, null=True)),
                ("melder_spiel_datum", models.DateField(blank=True, null=True)),
                ("melder_datum", models.DateField(blank=True, null=True)),
                ("sicher_zu_wasser_spiel_datum", models.DateField(blank=True, null=True)),
                ("sicher_zu_wasser_datum", models.DateField(blank=True, null=True)),
                (
                    "mitglied",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugend_ausbildung",
                        to="mitglieder.mitglied",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "ordering": ["mitglied__stbnr"],
            },
        ),
    ]
