# Generated by Django 4.2 on 2026-03-06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mitglieder", "0008_remove_mitglied_jugend_fields"),
        ("jugend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jugendevent",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("WISSENSTEST", "Wissentest"),
                    ("ERPROBUNG", "Erprobung"),
                    ("FWTECHNIK", "FW-Technik"),
                    ("MELDER", "Melder"),
                    ("SICHER_ZU_WASSER", "Sicher zu Wasser"),
                    ("SONSTIGES", "Sonstiges"),
                ],
                default="SONSTIGES",
                max_length=32,
                verbose_name="Kategorie",
            ),
        ),
        migrations.CreateModel(
            name="JugendEventTeilnahme",
            fields=[
                ("pkid", models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Erreichtes Level",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teilnahmen",
                        to="jugend.jugendevent",
                        verbose_name="Event",
                    ),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugend_event_teilnahmen",
                        to="mitglieder.mitglied",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "ordering": ["event__datum", "mitglied__stbnr"],
                "unique_together": {("event", "mitglied")},
            },
        ),
    ]
