# Generated by Django 4.2 on 2026-03-06

from django.db import migrations, models


def migrate_kategorie_values(apps, schema_editor):
    JugendEvent = apps.get_model("jugend", "JugendEvent")

    mapping = {
        "FWTECHNIK": "FERTIGKEITSABZEICHEN_FWTECHNIK",
        "MELDER": "FERTIGKEITSABZEICHEN_MELDER",
        "SICHER_ZU_WASSER": "FERTIGKEITSABZEICHEN_SICHER_ZU_WASSER",
        "SONSTIGES": "ERPROBUNG",
    }

    for old_value, new_value in mapping.items():
        JugendEvent.objects.filter(kategorie=old_value).update(kategorie=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ("jugend", "0002_jugendevent_kategorie_and_teilnahme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jugendevent",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("WISSENSTEST", "Wissentest"),
                    ("ERPROBUNG", "Erprobung"),
                    ("FERTIGKEITSABZEICHEN_MELDER", "Fertigkeitsabzeichen Melder"),
                    ("FERTIGKEITSABZEICHEN_FWTECHNIK", "Fertigkeitsabzeichen FW-Technik"),
                    (
                        "FERTIGKEITSABZEICHEN_SICHER_ZU_WASSER",
                        "Fertigkeitsabzeichen Sicher zu Wasser",
                    ),
                ],
                default="ERPROBUNG",
                max_length=64,
                verbose_name="Kategorie",
            ),
        ),
        migrations.RunPython(migrate_kategorie_values, migrations.RunPython.noop),
    ]
