# Generated by Django 4.2 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jugend", "0003_refine_event_kategorien"),
    ]

    operations = [
        migrations.AddField(
            model_name="jugendevent",
            name="stand_x_override",
            field=models.BooleanField(default=False, verbose_name="Voraussetzungen ausser Kraft"),
        ),
    ]
