# Generated by Django 4.1.7 on 2026-03-07 00:00

import core_apps.fahrzeuge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fahrzeuge", "0003_alter_fahrzeug_options_alter_fahrzeugcheck_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fahrzeug",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core_apps.fahrzeuge.models.fahrzeug_foto_filename,
                verbose_name="Foto",
            ),
        ),
        migrations.AddField(
            model_name="fahrzeug",
            name="service_naechstes_am",
            field=models.DateField(blank=True, null=True, verbose_name="Service naechstes am"),
        ),
        migrations.AddField(
            model_name="fahrzeug",
            name="service_zuletzt_am",
            field=models.DateField(blank=True, null=True, verbose_name="Service zuletzt am"),
        ),
        migrations.AddField(
            model_name="fahrzeugraum",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core_apps.fahrzeuge.models.fahrzeug_raum_foto_filename,
                verbose_name="Foto",
            ),
        ),
        migrations.AddField(
            model_name="raumitem",
            name="wartung_naechstes_am",
            field=models.DateField(blank=True, null=True, verbose_name="Wartung naechstes am"),
        ),
        migrations.AddField(
            model_name="raumitem",
            name="wartung_zuletzt_am",
            field=models.DateField(blank=True, null=True, verbose_name="Wartung zuletzt am"),
        ),
    ]
