# Generated by Django 4.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventar",
            name="ist_verliehen",
            field=models.BooleanField(default=False, verbose_name="Verliehen"),
        ),
        migrations.AddField(
            model_name="inventar",
            name="verliehen_an",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Verliehen an"),
        ),
        migrations.AddField(
            model_name="inventar",
            name="verliehen_bis",
            field=models.DateField(blank=True, null=True, verbose_name="Verliehen bis"),
        ),
    ]
