# Generated by Django 4.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventar", "0002_inventar_leihoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventar",
            name="verliehen_anzahl",
            field=models.PositiveIntegerField(default=0, verbose_name="Verliehene Anzahl"),
        ),
    ]
