# Generated by Django 4.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventar", "0003_inventar_verliehen_anzahl"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventar",
            name="verleihungen",
            field=models.JSONField(blank=True, default=list, verbose_name="Verleihungen"),
        ),
    ]
