# Generated by Django 4.2 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventar", "0004_inventar_verleihungen_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventar",
            name="wartung_naechstes_am",
            field=models.DateField(blank=True, null=True, verbose_name="Wartung naechstes am"),
        ),
        migrations.AddField(
            model_name="inventar",
            name="wartung_zuletzt_am",
            field=models.DateField(blank=True, null=True, verbose_name="Wartung zuletzt am"),
        ),
    ]
