# Generated by Django 4.1.7 on 2026-02-27 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Anwesenheitsliste",
            fields=[
                ("pkid", models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titel", models.CharField(max_length=255, verbose_name="Titel")),
                ("datum", models.DateField(blank=True, null=True, verbose_name="Datum")),
                ("ort", models.CharField(blank=True, max_length=255, verbose_name="Ort")),
                ("notiz", models.TextField(blank=True, verbose_name="Notiz")),
            ],
            options={
                "ordering": ["-datum", "titel"],
                "abstract": False,
            },
        ),
    ]
