# Generated by Django 4.1.7 on 2026-02-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mitglieder", "0001_initial"),
        ("anwesenheitsliste", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anwesenheitsliste",
            name="mitglied_id",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="mitglieder.mitglied"),
        ),
    ]
