# Generated by Django 5.2.11 on 2026-03-13 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mitglieder", "0008_remove_mitglied_jugend_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageDienstposten",
            fields=[
                ("pkid", models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_id", models.SlugField(max_length=80, verbose_name="Sektions-ID")),
                ("section_title", models.CharField(max_length=120, verbose_name="Sektions-Titel")),
                (
                    "section_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Sektions-Reihenfolge"),
                ),
                ("position", models.CharField(max_length=160, verbose_name="Position")),
                (
                    "position_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Positions-Reihenfolge"),
                ),
                (
                    "fallback_name",
                    models.CharField(default="Nicht definiert", max_length=255, verbose_name="Fallback Name"),
                ),
                (
                    "fallback_dienstgrad",
                    models.CharField(blank=True, max_length=50, verbose_name="Fallback Dienstgrad"),
                ),
                ("fallback_photo", models.CharField(default="X", max_length=32, verbose_name="Fallback Foto")),
                (
                    "fallback_dienstgrad_img",
                    models.CharField(blank=True, max_length=120, verbose_name="Fallback Dienstgrad Bild"),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homepage_dienstposten",
                        to="mitglieder.mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dienstposten",
                "verbose_name_plural": "Dienstposten",
                "ordering": ["section_order", "position_order", "position", "pkid"],
            },
        ),
    ]
