# Generated by Django 5.2.11 on 2026-03-13 13:20

import core_apps.homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_seed_default_dienstposten"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagedienstposten",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core_apps.homepage.models.homepage_photo_path,
                verbose_name="Foto Datei",
            ),
        ),
    ]
