# Generated by Django 5.2.11 on 2026-03-05 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTemplate',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Vorlagenname')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('typ', models.CharField(default='intern', max_length=255, verbose_name='Typ')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'News-Vorlage',
                'verbose_name_plural': 'News-Vorlagen',
                'ordering': ['name', 'created_at'],
            },
        ),
    ]
